version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: financeapp-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_app
    ports:
      - "5432:5432"       # host:container
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
